### PR TITLE
ENG-678 Refactor: examples/react/complete w/ oreid-js@v3 

### PR DESCRIPTION
**Pull request by artmanque**

### CODE REVIEW

**Review by dhruv-kumar-jha — DISMISSED** [review]

**Comment by deckb** [comment]
Seeing this error when I run the app:
```
Missing required parameter(s) for API account/user: account
```
image

**Review by deckb — COMMENTED** [review]
Other than the other issue I commented on earlier this looks good.

**Comment by artmanque** [comment]
> Seeing this error when I run the app:
> 
> ```
> Missing required parameter(s) for API account/user: account
> ```
> 
> image

this is thrown by oreid-js to indicate there was no user id found

**Comment by artmanque** [comment]
The error prompt is infact a result of that particular error handling, the user gets logged out and see how oreid resonds to it. From: Buddy Deck ***@***.***>Sent: Friday, April 1, 2022, 6:14 PMTo: TeamAikon/ore-id-docs ***@***.***>Cc: Abdul R. Tay ***@***.***>; Author ***@***.***>Subject: Re: [TeamAikon/ore-id-docs] ***@***.*** ENG-678 (PR #125)

this is thrown by oreid-js to indicate there was no user id found

Probably something that should be handled if no one is logged in but not a blocker for this work. I'm good with this PR.

**Comment by artmanque** [comment]
> > this is thrown by oreid-js to indicate there was no user id found
> 
> Probably something that should be handled if no one is logged in but not a blocker for this work. I'm good with this PR.

the error prompt is the error handling of the error thrown by oreid-js. The raw messages are passed along to illustrate how oreid-js reacts in those scenarios

**Comment by deckb** [comment]
> > > this is thrown by oreid-js to indicate there was no user id found
> > 
> > 
> > Probably something that should be handled if no one is logged in but not a blocker for this work. I'm good with this PR.
> 
> the error prompt is the error handling of the error thrown by oreid-js. The raw messages are passed along to illustrate how oreid-js reacts in those scenarios

Understood but I wouldn't expect it to show up when running the app for the first time and I haven't logged in.

This is obviously not a huge problem but when a developer attempts to run the app and they see an error first thing that doesn't seem ideal to me.

**Comment by artmanque** [comment]
> > > > this is thrown by oreid-js to indicate there was no user id found
> > > 
> > > 
> > > Probably something that should be handled if no one is logged in but not a blocker for this work. I'm good with this PR.
> > 
> > 
> > the error prompt is the error handling of the error thrown by oreid-js. The raw messages are passed along to illustrate how oreid-js reacts in those scenarios
> 
> Understood but I wouldn't expect it to show up when running the app for the first time and I haven't logged in.
> 
> This is obviously not a huge problem but when a developer attempts to run the app and they see an error first thing that doesn't seem ideal to me.

The app runs on localhost:3000 which had cached an accessToken. OreId instance tried to log you in with that but was unable to which threw that error. For a new user login experience, try to login in a private window

**Pull request merged**
